# RELATÓRIO GERENCIAL (API: ECCO, FB E GA)


### PROBLEM: I DONT HAVE DIRECT INFORMATION OF DISCOUNT BY PRODUCT ON ORDERS, ONLY ORDER DISCOUNT AND THE DISCOUNT BY
### PRODUCT ONLY IN NFS AND IF I WANTED THE INFORMATION BY PRODUCT I WOULD HAVE TO MAKE A CALCULATION THAT I AM AFRAID COULD BE WRONG
