name: Scheduled [Lofty - product_order_snap_v1]

on:
  schedule:
    - cron: '30 10 * * *'  # Every day at 07:30 AM (BRT) 

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      SUPABASE_LOFTY_KEY: ${{ secrets.SUPABASE_LOFTY_KEY }}
      SUPABASE_LOFTY_URL: ${{ secrets.SUPABASE_LOFTY_URL }}

      
    strategy:
      matrix:
        python-version: [3.11]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies 2
        run: |
          pip install pandas==2.1.4 python-dotenv requests workalendar supabase numpy

      - name: Run Code Lofty product_order_snap_v1
        run: |
          python product_order_snap_v1.py



        
