name: Scheduled [lofty_ga_summary_v1]

on:
  schedule:
    - cron: '15 6 * * *'  # Every day at 03:15 AM (BRT) 
    - cron: '15 9 * * *'  # Every day at 06:15 AM (BRT) 

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      ga_id_lofty: ${{ secrets.GA_ID_LOFTY }}    
      SUPABASE_LOFTY_KEY: ${{ secrets.SUPABASE_LOFTY_KEY }}
      SUPABASE_LOFTY_URL: ${{ secrets.SUPABASE_LOFTY_URL }}
      
    strategy:
      matrix:
        python-version: [3.11]
        
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set timezone to GMT-3
        run: |
          sudo timedatectl set-timezone America/Sao_Paulo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies 2
        run: |
          pip install pandas==2.1.4 python-dotenv requests supabase numpy datetime workalendar google-analytics-data
      
      - name: Decode and save Google credentials
        run: |
          echo ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }} | base64 --decode > $GITHUB_WORKSPACE/mage---performan-1705337009329-52b7dddd6d54.json

      - name: Run Code ga_api
        run: |
          python lofty_ga_summary.py

        
