name: Scheduled [rel_ger_ecco_api_v1.0]

on:
  schedule:
    - cron: '15 3 * * *'  # Every day at 12:15 AM (BRT) 

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      ecco_aut_mun: ${{ secrets.ECCO_AUT_MUN }}
      fb_act_mun: ${{ secrets.FB_ACT_MUN }}
      fb_llt: ${{ secrets.FB_LLT }}
      ga_id_mun: ${{ secrets.GA_ID_MUN }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}      
      
    strategy:
      matrix:
        python-version: [3.11]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies 2
        run: |
          pip install pandas==2.1.4 python-dotenv requests workalendar supabase google.analytics.data_v1beta

      - name: Run Code Eccosys API
        run: |
          python rel_ger_ecco_api_v1.0.py

      - name: Run Code FB API
        run: |
          python rel_ger_fb_api_v1.0.py

      - name: Run Code GA API
        run: |
          python rel_ger_ga_api_v1.0.py
